### ISSUE TITLE
Terminal says Unsupported Operating System (MacOS)

### ISSUE THREAD

**Issue by NxthanWasTaken** [LeadRDRK/finobe-linux-wrapper#5]
Due to Catalina removing support for 32 bit, it does not work. I am here standing by waiting if developers going to notice they need to make 64 bit version for MacOS Catalina and such as Big Sur. You could teach me on how to run as 64 bit instead of 32 bit.

**Comment by LeadRDRK** [comment]
macOS is simply not supported. Here's why:
1. The script provides URI handlers for XDG which is only available on Linux
2. Even if it supported macOS, Finobe will still not run due to a missing component in Wine on macOS. The launcher will simply fail to connect to the server.
And it's not like we can add or install it or anything.

Closing due to unsupported platform.
